### ISSUE TITLE
Revise Indication Board

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/pcb_designs#20]
This board is important now.

New competition rules say we need a bright RGB indicator board to say what autonomy modes we are in.

Chages to be made: instead of 8 low power RGB leds we need one or two higher power ones. Also the CAN connectors need to be changed, and possibly a programming header.

**Comment by davidlenfesty** [comment]
To find the LED driver, go to digikey, find the IC -> PMIC LED Driver category, and search fo linear types with 3 outputs, and you will have to figure out the current needed, and find an appropriate LED as well.

**Comment by jopgen** [comment]
Closing, this is no longer needed
