### ISSUE TITLE
Finish Setting up Arm

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/pcb_designs#23]
Once mechanical team has the tray system, we will need to integrate the arm fully into the rover.

Tasks:
- [ ] Make connectors, etc. to hook up sensors and motors on the arm.
- [ ] Finish fixing firmware, ensure it works with arm board rev. 2
- [ ] Hook in arm, configure arm controllers.

**Comment by minh7a6** [comment]
what type of sensors are we gonna put in the arm besides encoder?

**Comment by davidlenfesty** [comment]
Just the different arm encoders
